services:
#   web:
#     build: .
#     ports:
#       - "8000:8000"
#     depends_on:
#       - redis
#     environment:
#       - DJANGO_SETTINGS_MODULE=finance_management.settings
#       - REDIS_HOST=redis
#     volumes:
#       - .:/app

  websocket:
    build: .
    command: daphne -b 0.0.0.0 -p 8001 finance_management.asgi:application
    ports:
      - "8001:8001"
    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=finance_management.settings
      - REDIS_HOST=redis
    volumes:
      - .:/app

  redis:
    image: redis:latest
    ports:
      - "6379:6379"