# Generated by Django 5.0.2 on 2024-12-22 21:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonusrequest',
            name='attachment',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='bonus_attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'png'])]),
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
